on:
  push:
jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build container
      run: |
        nix build .#container
        mv result container.tar.gz
    - name: Upload container
      uses: actions/upload-artifact@v4
      with:
        name: container
        path: container.tar.gz
