on:
  push:
jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build container
      run: |
        nix build .#container
    - name: Upload container
      uses: actions/upload-artifact@v4
      with:
        path: result
